export const SET_DATA = 'SET_DATA';
export const CREATE_DATA_ITEM = 'ADD_DATA_ITEM';
export const UPDATE_DATA_ITEM = 'UPDATE_DATA_ITEM';
export const DELETE_DATA_ITEM = 'DELETE_DATA_ITEM';

export const SET_LOADING = 'SET_LOADING';
export const SET_CREATING = 'SET_CREATING';
export const SET_UPDATING = 'SET_UPDATING';
export const SET_DELETING = 'SET_DELETING';

export const SET_ERROR_LOADING = 'SET_ERROR_LOADING';
export const SET_ERROR_CREATING = 'SET_ERROR_CREATING';
export const SET_ERROR_UPDATING = 'SET_ERROR_UPDATING';
export const SET_ERROR_DELETING = 'SET_ERROR_DELETING';
